tinymce/bedrock

- changelog.txt
- modules/server/package.json
- yarn.lock
This fixes the security advisor flagged by GitHub and just does a general update as well.
> Upgraded bedrocks dependencies

- changelog.txt
- modules/sample/package.json
- modules/sample/src/test/js/client/SyncPassTest.js
- modules/server/src/main/ts/bedrock/compiler/Imports.ts
I noticed that the import file was corrupt when updating bedrock to the latest version.
> fixed import generation for js tests

- changelog.txt
- modules/server/src/main/ts/bedrock/compiler/Imports.ts
I'm not entirely sure why, but it seems as though webpack or one of the loaders we're using ends up in an infinite compilation loop when there's too many try/catch statements.
Previously we had a try/catch statement for each test, however to prevent the infinite loop I've changed this back to just one global catch all. This does mean other tests can't run if one has an import error, but at least with this change we'll still know that tests failed to run.
Here's an example of what the failure looks like:
```
-------------------------------------------------------------------------------
Test failed: Import Error - src/test/ts/client/SyncPassTest.ts (undefined)
TypeError: undefined is not a function (evaluating 'window.blah()')
Logs: …
```
> TINY-4713: Fixed bedrock ending up in an infinite compilation loop

- CODEOWNERS
- changelog.txt
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
Follow up to TINY-4269, which only fixed TypeScript source maps (and the "unused param" was later removed)
> Restored JS source maps

- changelog.txt
- modules/runner/src/main/ts/core/Runner.ts
- modules/runner/src/main/ts/core/Utils.ts
- modules/runner/src/main/ts/ui/Actions.ts
- modules/runner/src/test/ts/core/UtilsTest.ts
This was caused by the `loadNextTest` not actually increasing the offset, so it never actually automatically moved to the next test. I also found out the failed count wasn't being updated when retrying either and the retry functionality didn't work if the very first test failed (both were older issues).
> TINY-6204: Fixed tests getting stuck when reaching the maximum retry count

- changelog.txt
- modules/server/package.json
- modules/server/src/main/ts/bedrock/cli/Extraction.ts
- modules/server/src/test/ts/ValidationTest.ts
- yarn.lock
As a side effect of this, `--testdir` can now use globs to search multiple directories (on windows, *nix will still fail because the shell expands it). This happened because difference between `--testdir` and `--testdirs` is only in the command line parsing, they have identical implementations. I figured this was ok.
> TINY-6218: Use glob to improve test directory scanning on windows

- changelog.txt
- modules/server/src/main/ts/bedrock/auto/Driver.ts
When using the latest version of 3.x for IEDriverServer, the `deleteSession()` call is being ignored when called too quickly, so we just need to introduce a small delay.
Have tested this branch using the driver from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/Win32/Release (3.105.1.1)
> Fixed IE 11 not shutting down with newer IEDriverServer versions

- changelog.txt
- modules/sample/package.json
- modules/sample/src/test/ts/client/BddPassTest.ts
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/BedrockCli.ts
- modules/server/src/main/ts/BedrockFramework.ts
- modules/server/src/main/ts/BedrockManual.ts
- modules/server/src/main/ts/bedrock/cli/ClOptions.ts
- modules/server/src/main/ts/bedrock/cli/Clis.ts
- modules/server/src/main/ts/bedrock/compiler/Compiler.ts
- modules/server/src/main/ts/bedrock/compiler/Imports.ts
- modules/server/src/main/ts/bedrock/compiler/Rollup.ts
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
- modules/server/src/main/ts/bedrock/core/Settings.ts
- modules/server/src/main/ts/bedrock/server/CustomRoutes.ts
- modules/server/src/main/ts/bedrock/server/RunnerRoutes.ts
- modules/server/src/main/ts/bedrock/server/Serve.ts
- modules/server/src/test/ts/ClisTest.ts
- modules/server/src/test/ts/compiler/ImportsTest.ts
This adds the ability to include additional polyfills as part of the test run by adding for example `--polyfills Promise Symbol`. The default is `Symbol` to keep backwards compatibility and I didn't add `Promise` as part of that as discussed with the Editor Team on slack.
This will allow us to write `async`/`await` tests in TinyMCE and rely on the Promise eslint rule to ensure we don't misuse a Promise for IE 11.
> TINY-6732: Updated bedrock to support pulling in specified polyfills

- CODEOWNERS
- changelog.txt
- modules/runner/src/main/ts/reporter/Callbacks.ts
- modules/sample/src/test/ts/client/BddPassTest.ts
If a test title contains ?? then the test fails with the error message [object Object]. This is because we're not setting the content type, so it's treating the string as "application/x-www-form-urlencoded" and that tries jQueries magic ?? replacement logic. See: https://api.jquery.com/jquery.ajax/
Note: I've also updated the CODEOWNERS to better reflect the current reviewers for bedrock
> TINY-6732: Fixed tests failing if the title contained "??" in the title

- changelog.txt
- modules/runner/src/main/ts/runner/Hooks.ts
- modules/runner/src/test/ts/runner/HooksTest.ts
See the JIRA for more details and a replication case in Mocha to show this is how it should be working.
> TINY-6882: Fixed beforeEach and afterEach hooks running in the wrong order

- changelog.txt
- modules/runner/src/main/ts/reporter/Callbacks.ts
- modules/runner/src/main/ts/reporter/Reporter.ts
- modules/runner/src/main/ts/runner/Runner.ts
- modules/runner/src/test/ts/reporter/ReporterTest.ts
- modules/server/src/main/ts/bedrock/server/Apis.ts
- modules/server/src/main/ts/bedrock/server/Controller.ts
Note: I haven't written any tests for the server part, as there are none. We're going to have to handle that tech debt one day though, so I'll log a JIRA so we can schedule it (see TINY-6898).
> TINY-6897: Fixed bedrock not returning a non-zero error code when tests unexpectedly stopped

- changelog.txt
- modules/server/src/main/ts/bedrock/cli/ClOptions.ts
- modules/server/src/main/ts/bedrock/compiler/Imports.ts
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
- modules/server/src/test/ts/compiler/ImportsTest.ts
We are in the process of switching to `.mjs` files in RTC in order to satisfy the NodeJS requirements for using a mixed ESM/CJS environment.
However Webpack applies a very strict `javascript/esm` type to `.mjs` files which make it much more difficult to import CommonJS modules. The error that it throws is `Can't import the named export <blah> from non EcmaScript module (only default export is available)`. That's not easy to google for, many have had this issue and it took a while to track down the best workaround. The solution is to redefine `.mjs` files as the more general `javascript/auto` type.
This PR makes a few changes:
* Adds `Test.mjs` to the CLI `testdir` extension search list
* Side note: we can potentially remove `Test.bs.js` now but that extension might be useful for other …
> TINY-6970: Add .mjs file support

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/server/Apis.ts
This makes Chrome Edge match how Chrome works when running tests and also fixes some flakes we've been seeing lately.
> TINY-7039: Enable the mouse position reset logic on Microsoft Edge

- CHANGELOG.md
- modules/client/src/main/ts/api/LegacyAssert.ts
- modules/client/src/main/ts/core/Compare.ts
- modules/common/src/main/ts/api/ErrorExtractor.ts
- modules/common/src/main/ts/api/Main.ts
- modules/common/src/main/ts/api/Reporter.ts
- modules/common/src/main/ts/api/TestError.ts
- modules/common/src/test/ts/api/ReporterTest.ts
- modules/runner/src/main/ts/reporter/Callbacks.ts
- modules/runner/src/main/ts/reporter/Reporter.ts
- modules/runner/src/test/ts/reporter/ReporterTest.ts
- modules/server/package.json
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/bedrock/cli/Clis.ts
- modules/server/src/main/ts/bedrock/core/ConsoleReporter.ts
- modules/server/src/main/ts/bedrock/core/Lifecycle.ts
- modules/server/src/main/ts/bedrock/core/Reporter.ts
- modules/server/src/main/ts/bedrock/server/Controller.ts
- yarn.lock
This is something I've been wanting to do as a "pet" project for quite a long time, as the errors reported via the terminal can be very hard to read. More than happy to change the colours I've used if anyone has better suggestions.
Description of changes:
- Reworked the error printing logic to generate a normalized `ErrorData` object from the various `Error` types. From that the errors can be formatted in a consistent way.
- Updated the runner and server to pass through the new `ErrorData` object instead of just a plain text string when a test fails. This also could open up the ability to have different reporters in the future if we want/need it.
- Changed the legacy assertion module to throw an Assertion error. This is done so that we can highlight the diff, as previously it was all part …
> Added support to print coloured output in the terminal

- CHANGELOG.md
- modules/common/src/main/ts/api/Failure.ts
- modules/runner/src/main/ts/api/Main.ts
- modules/runner/src/main/ts/runner/Runner.ts
This just fixes 2 minor issues I found when spiking out a new feature I want to implement for Bedrock (looking at improving stack traces). The first was there were 2 files we weren't using the Promise polyfill which meant the runner died on IE in specific cases. The second is that on Firefox the stacktrace starts on line 0, not line 1 like other browsers so we were losing the first entry.
Note: We can't use automated tests for either of these as the tests run using Node.js.
> Minor fixes

- CHANGELOG.md
- modules/runner/package.json
- modules/runner/src/main/ts/core/Utils.ts
- modules/runner/src/main/ts/reporter/Reporter.ts
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
- package.json
- patches/sourcemapped-stacktrace+1.1.11.patch
- yarn.lock
This updates the runner to use the `sourcemapped-stacktrace` library to process the stack traces produced for failed tests and remap them using the generated source maps where they exist. This means that we'll get actual useful file names and line numbers for errors that occur instead of it just saying `tests.js`. As part of this, it does mean that we always generate a sourcemap with webpack now.
Note: Unfortunately, I did find some bugs/inconsistencies with the way the `sourcemapped-stacktrace` library worked, so it did need some patches. The patches I've done are safe in the context of bedrock (since we're always running via http), but probably aren't safe for general use so I haven't looked at contributing them back. Part of the issue was that the library only currently worked with …
> TINY-7869: Add sourcemap resolution for stack traces

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/server/Apis.ts
- modules/server/src/resources/css/bedrock.css
- modules/server/src/resources/html/bedrock-phantom.html
- modules/server/src/resources/html/bedrock.html
This swaps the action used to reset the mouse position between tests on Chrome and Edge. For those that don't know the history, chromium browsers like to fire mouseover, etc... events for where the actual mouse, even when it's not moved, which can cause test flakes.
This version is ~3x faster than the old version (~10ms vs ~30ms), so while that's not much for a single test, when you have 5000+ tests as we do in TinyMCE, then it saves ~1&half; minutes.
> TINY-7918: Improved the test execution speed on Chrome and Edge

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
RTC runs a dual NodeJS + Bedrock test setup and some of the NodeJS-isms are too tightly integrated to remove easily.
This wasn't a problem with Webpack 4, it auto-bundles a lot of polyfills, but Webpack 5 stopped doing that.
I can manage `assert` and `util` by adding the webpack 4 versions as RTC dependencies but these polyfills still expect a `process` global. The only option I've found to mange code that uses `process.env` is a `DefinePlugin` (which does string replacement on bundled files).
I only did this to JS mode; I figure TypeScript code is less likely to need them.
> TINY-7971: Added node environment definitions to webpack in JS mode

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
This just makes some changes to improve inconveniences I found when getting this working in TinyMCE:
- Bedrock manual mode will now use inline source maps. They take about the same time to generate but ensures the source maps don't run into caching issues or similar when running in watch mode.
- Adds a few more paths to ignore to prevent webpack doing multiple compilations when not necessary.
> TINY-7654: Use inline source maps for manual mode and ignore more changes

- CHANGELOG.md
- modules/runner/package.json
- modules/runner/src/main/ts/api/Main.ts
- modules/runner/src/main/ts/core/TestLoader.ts
- modules/runner/src/main/ts/core/Utils.ts
- modules/runner/src/main/ts/reporter/Callbacks.ts
- modules/runner/src/main/ts/reporter/Reporter.ts
- modules/runner/src/main/ts/runner/Hooks.ts
- modules/runner/src/main/ts/runner/Run.ts
- modules/runner/src/main/ts/runner/Runner.ts
- modules/runner/src/main/ts/runner/TestRun.ts
- modules/runner/src/main/ts/runner/Utils.ts
- modules/runner/src/test/ts/reporter/ReporterTest.ts
- modules/runner/src/test/ts/runner/RunnerTestUtils.ts
- modules/runner/src/test/ts/runner/TestRunTest.ts
- modules/runner/src/test/ts/runner/UtilsTest.ts
- modules/runner/tsconfig.json
- modules/sample/package.json
- modules/sample/src/test/ts/client/fail/AsyncFailTest.ts
- modules/sample/src/test/ts/client/pass/AsyncPassTest.ts
- modules/sample/tsconfig.json
- yarn.lock
This reverts commit 3312705b1fa8a7c2b3c8ec1110250aa36ec6119a.
Upon trying to upgrade to 12.3.0 Andy noticed things got a lot slower, which when we investigated we found the library never attempted to use the global and instead it was the contact wrapper that was using the global if available. As such for now we're just going to revert this and remove polyfilling altogether in the next major (we want to upgrade to the latest webpack-dev-server so will likely do it then).
> TINY-8293: Revert swapping to use `promise-polyfill` directly

- CHANGELOG.md
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/bedrock/auto/Driver.ts
- modules/server/src/main/ts/bedrock/core/Lifecycle.ts
- modules/server/src/main/ts/bedrock/core/Settings.ts
This was something I accidentally broke in 12.0.0 via https://github.com/tinymce/bedrock/pull/74. The problem is if a successful shutdown happens the `driverApi.stop()` function wasn't being called. That in turn meant the webdriver process would keep running forever depending on the shell/terminal being used. Additionally, if an unexpected runner error occurred it wasn't doing a graceful server shutdown and instead did a forced shutdown (since the `Reporter.writePollExit` call returns a rejected promise).
> TINY-8403: Fixed the server not always getting shutdown correctly

- CHANGELOG.md
- modules/runner/src/main/ts/runner/Run.ts
- modules/runner/src/main/ts/runner/Runner.ts
- modules/runner/src/test/ts/runner/RunnerTestUtils.ts
- modules/runner/src/test/ts/runner/TestRunTest.ts
If a bedrock configured/default timeout occurred, then the wrong timeout value was reported in the error messages. This means you would have ended up with something like `Error: Test ran too long - timeout of -1ms exceeded`, so this ensures the correct timeout value is set for the runnable as that'll make sure if it's looked up in the test it has the right value as well.
Note: Also fixed a minor issue with the URL being shown incorrectly based on the state when a test is retried and then passes.
> TINY-8189: Fixed the wrong timeout value being reported

- CHANGELOG.md
- modules/client/src/main/ts/core/Compare.ts
- modules/common/src/main/ts/api/Main.ts
- modules/common/src/main/ts/api/Type.ts
- modules/common/src/test/ts/api/TypeTest.ts
- modules/runner/src/main/ts/errors/ErrorCatcher.ts
- modules/runner/src/test/ts/errors/ErrorCatcherTest.ts
This fixes uncaught errors thrown within frames not getting their stack trace used due to the `instanceof Error` check failing. I've moved the `Type` module to bedrock common since it's now used by the client and runner (remember we can't use katamari).
> TINY-8165: Fixed cross frame uncaught errors not handled correctly

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/auto/Driver.ts
- modules/server/src/main/ts/bedrock/auto/DriverLoader.ts
Not all webdrivers support ipv6 and Node.js 17 will now attempt to use it when resolving hostnames, so this just forces it to use `127.0.0.1` which all webdrivers support.
> TINY-8408: Ensure webdriver.io uses 127.0.0.1 when trying to connect to the webdriver

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
I've removed this as we found while investigating performance issues that these a) don't appear to be needed anymore and b) are causing things to have to be recompiled, especially with incremental builds.
> TINY-8299: Removed TypeScript compiler overrides

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/compiler/Webpack.ts
This was done as the `stats.warningsFilter` is now deprecated and doesn't seem to be respected for the overlay, so I've moved the filter to the appropriate place for Webpack 5, combined with Webpack Dev Server 4.
> TINY-8414: Fixed an issue where the webpack-dev-server overlay would show for re-exported types

- CHANGELOG.md
- modules/runner/src/main/ts/reporter/Callbacks.ts
- modules/runner/src/main/ts/runner/Runner.ts
- modules/runner/src/test/ts/reporter/ReporterTest.ts
- modules/server/src/main/ts/bedrock/cli/ClOptions.ts
- modules/server/src/main/ts/bedrock/server/Apis.ts
This improves when the mouse reset position logic happens for bedrock auto mode, so that it only does it when required instead of for every single test. This should help to speed up our Chrome and Edge tests, especially on the M1 nodes (TinyMCE went from 9mins down to about 4mins in my testing).
The idea behind this change is to make it so that the mouse position only resets at the start of the runner init sequence (e.g. on first run and then on page reloads for test failures) and also when a previous test moves the mouse around.
> TINY-8502: Improve when mouse position resets occur

- CHANGELOG.md
- modules/server/package.json
- package.json
- yarn.lock
This removes the unused `node-glob` dependency which has deps on packages with security issues. It also hasn't been maintained in 6yrs. I've also upgraded the dev dependencies as well to resolve as many dependabot security alerts as I can.
> TINY-8717: Removed the unused node-glob dependency

- CHANGELOG.md
- modules/runner/src/main/ts/core/Utils.ts
- modules/runner/src/main/ts/errors/ErrorCatcher.ts
- modules/runner/src/main/ts/reporter/Reporter.ts
- modules/sample/src/test/ts/client/ClipboardTest.ts
- modules/sample/src/test/ts/client/pass/EffectsTest.ts
- modules/sample/src/test/ts/client/pass/IFramePassTest.ts
- modules/sample/src/test/ts/utils/Utils.ts
- modules/server/package.json
- modules/server/src/main/ts/bedrock/server/KeyEffects.ts
- yarn.lock
Related Ticket: TINY-8944
Changed how the key effects logic works when using a combo key effect so that it uses the webdriver.io `keys` API instead to ensure modifier keys are released properly. Note that this can't be used at all times, as we need to use `elementSendKeys` when actually typing text otherwise it won't show.
I also fixed an issue I found when trying to debug whereby a `TypeError: Attempted to assign to readonly property` would get thrown instead on PhantomJS due to `stack` being a readonly property. So we just skip setting the stack in that case, even if it means the stack is no longer useful as it's only an issue on PhantomJS.
Pre-checks:
* For release candidates, all …
> TINY-8944: Fixed the key effects leaving modifier keys active on Safari

- CHANGELOG.md
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/bedrock/auto/Driver.ts
- modules/server/src/main/ts/bedrock/cli/ClOptions.ts
- modules/server/src/main/ts/bedrock/core/Settings.ts
- modules/server/src/test/ts/ClisTest.ts
Related Ticket: TINY-8703
* Updates how the default debugging port is generated so that it scans for an available port instead of being hardcoded to port 9000.
* Adds a console log when running in headless mode to print the debugger information
* Minor refactoring as to how headless mode is detected
* Allow `edge` to be used as a short hand alias for `MicrosoftEdge`
Pre-checks:
> TINY-8703: Improved the headless debugging port handling

- Jenkinsfile
- package.json
Related Ticket: TINY-9097
* Upgrade to the latest version of waluigi to build using containers
* Changed `yarn test` to not run the sample project tests since they are all run on the browsers anyways
Pre-checks:
> TINY-9097: Upgrade to the latest waluigi version

- Jenkinsfile
Related Ticket: TINY-9097
Lerna publish fails to run if there are uncommited changes and because we have to set npm config for the auth token this failed. So we now tell Git to ignore those changes before publishing.
Pre-checks:
> TINY-9097: Fixed lerna publish issues with new waluigi version

- CHANGELOG.md
- modules/sample/src/test/ts/client/pass/IFramePassTest.ts
- modules/server/package.json
- modules/server/src/test/ts/AttemptTest.ts
- modules/server/tsconfig.json
- package.json
- yarn.lock
Related Ticket: TINY-9852
* Bumped webdriverio version
* Fixed type errors
* Skipped type checking in the dependencies as there are type errors in webdriverio package
Pre-checks:
> TINY-9852: Upgraded dependencies

- CHANGELOG.md
- modules/server/package.json
- yarn.lock
Related Ticket: TINY-9855
the problem seems to be the 2 different version of `fork-ts-checker-webpack-plugin`
Pre-checks:
> TINY-9855: fix for watch mode

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/auto/Driver.ts
Related Ticket: TINY-10014
* Guest mode in MS Edge is really what the webdriver should use by default, but here we go. At the moment it's disabling the new "Personalize your web experience" popup, which takes focus on windows.
* I also added the browser name to the startup console log, this helped with some debugging I was doing during development and it seemed useful so I left it in.
Pre-checks:
> TINY-10014: Add --guest argument for MSEdge

- .editorconfig
- CHANGELOG.md
- modules/server/src/main/ts/bedrock/server/Routes.ts
- modules/server/src/main/ts/bedrock/server/RunnerRoutes.ts
Related Ticket: TINY-10281
* Added missing .editorconfig file
* Added new node resolve based routes
* Cleaned up the concat of routes so that it uses the spread operator instead
Pre-checks:
> TINY-10281: Added node_module resolve routes

- CHANGELOG.md
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/bedrock/auto/Driver.ts
- modules/server/src/main/ts/bedrock/auto/RemoteDriver.ts
- modules/server/src/main/ts/bedrock/cli/ClOptions.ts
- modules/server/src/main/ts/bedrock/cli/Clis.ts
- modules/server/src/main/ts/bedrock/core/Settings.ts
- modules/server/src/test/ts/ClisTest.ts
Related Ticket: TINY-10466
* Add browserVersion and platformName args for remote testing
Pre-checks:
> TINY-10466: Add browserVersion and platformName args

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/server/MouseEffects.ts
Related Ticket: TINY-10490
to test the issue for `TINY-10490` I need a real right click, I think this feature could be useful also for other tests
Pre-checks:
> TINY-10490: add mouse right click

- CHANGELOG.md
- modules/server/src/main/ts/BedrockAuto.ts
- modules/server/src/main/ts/bedrock/auto/Driver.ts
- modules/server/src/main/ts/bedrock/auto/RemoteDriver.ts
- modules/server/src/main/ts/bedrock/auto/Tunnel.ts
- modules/server/src/main/ts/bedrock/core/Lifecycle.ts
- Pass tunnel name for webdriver
- Use LT project naming
- Mark LT test results
Related Ticket: TINY-10604
* Placeholder text
Pre-checks:
* [-] package.json versions have not been changed (done by Lerna on release)
* [-] Tests have been added (if applicable)
* [-] Ensure internal dependencies are on appropriate versions
> TINY-10604: LambdaTest improvements

- CHANGELOG.md
- modules/server/src/main/ts/bedrock/server/RunnerRoutes.ts
Related Ticket: TINY-10688
If the `workspaces` prop inside of the project's `package.json` is unused, check if there's a `pnpm-workspace.yaml` file then use `pnpm list -r --only-projects --json` to find workspaces instead.
Pre-checks:
> TINY-10688: Support using `pnpm-workspace.yaml`

- CHANGELOG.md
- modules/sample/src/test/ts/client/pass/EffectsTest.ts
- modules/server/src/main/ts/bedrock/util/Env.ts
Related Ticket: TINY-10801
IS_CI is now checking for _not_ TTY.
Pre-checks:
> TINY-10801: `IS_CI` should be checking `!isTTY`

- modules/server/src/main/ts/bedrock/auto/RemoteDriver.ts
I don't think we need to hide this logging behind a CLI option
Related Ticket: TINY-11252
* Enable terminal and network logging for lambdatest
Pre-checks:
> TINY-11252: Add terminal and network logging

- CHANGELOG.md
- modules/runner/src/main/ts/reporter/Reporter.ts
Related Ticket: TINY-11177
* While running tests with bedrock 15 I noticed that Firefox was sometimes hitting the server-side timeout after tests failed and were retried.
* I tracked this down to code I added which [hides the test under retry from the server](https://github.com/tinymce/bedrock/blob/867332a4c25a86e7f0c9505c22414e8d42148e79/modules/runner/src/main/ts/reporter/Reporter.ts#L205-L210). As a result, if the client did a retry with no other test results to report no message would be sent to the server.
* This turns out to conflict with other optimisations that don't send any messages to the server after a reload until 30 seconds have passed.
* Remote selenium has slower load times, so if the retry took long enough this would bump into the server-side time …
> TINY-11177: Ensure that a failed/retry test that passes is reported immediately
